apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworld-k8s
spec:
 replicas: 2
 selector:
  matchLabels:
   app: helloworld-k8s
 template:
  metadata:
   labels:
    app: helloworld-k8s
  spec:
   containers:
    - name: helloworld-k8s
      image: myjobsashdocker/helloworld:latest
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 8080