apiVersion: v1
kind: Service
metadata:
 name: helloworld-k8s-service
spec:
 selector:
  app: helloworld-k8s
 ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 31200
 type: NodePort