version: '3.8'

services:
  app:
    image: loginservice
    restart: always
    ports:
     - 8080:8080
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/privatecloud?qutoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&enabledTLSProtocols=TLSv1.2
     SPRING_DATASOURCE_USERNAME: admin
     SPRING_DATASOURCE_PASSWORD: root
    depends_on:
     - db

  db:
   image: mysql
   environment:
    DATABASE_HOST: mysql
    DATABASE_PORT: 3306
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: privatecloud
    MYSQL_USER: admin
    MYSQL_PASSWORD: root